### ISSUE TITLE
Use permalink for Wavu wiki logo in embed footer

### ISSUE THREAD

**Issue by AbhijeetKrishnan** [TLNBS2405/heihachi#2]
Currently, a [hardcoded url](https://github.com/TLNBS2405/heihachi/blob/master/src/module/embed.py#L65) is used for the Wavu wiki logo in the footer that points to an outdated version of the logo. The current logo can be found at this permalink.

[`https://wavu.wiki/android-chrome-192x192.png`](https://wavu.wiki/android-chrome-192x192.png)

Using this should guarantee that the logo retrieved is always the current version of the logo at 192x192 resolution.

**Comment by TLNBS2405** [comment]
Done
