### ISSUE TITLE
Does not link to Devil Jin's moveset

### ISSUE THREAD

**Issue by ChaoticNPC** [TLNBS2405/heihachi#9]
When attempting to use the bot for Devil Jin, the bot returns with a "Move not found" error. I've tested multiple moves and the bot doesn't recognize any moves from Devil Jin.

**Comment by AbhijeetKrishnan** [comment]
This is likely because the DJ move ids on Wavu are of the form `Devil Jin-` whereas the bot expects it to be something like `Devil_jin-`. This could be handled by replacing all the move IDs on Wavu or by changing the logic in `wavu_reader.py`.
